### ISSUE TITLE
Kernel nvidia_desunix_long__sm21.ptx does not exist

### ISSUE THREAD

**Issue by grk-** [gat3way/hashkill#17]
i compiled latest hashkill and tried it over a old unix DES passwd file but unfortunately got the following error:

grk@higgs:/usr/local/bin$ ./hashkill -p desunix -f passwd_di.txt --brute='1:10:alphanum'

[hashkill] Version 0.3.0
[hashkill] Scheduler initialized.
[hashkill] Plugin 'desunix' loaded successfully
[hashkill](passwd_di.txt): 1 hashes loaded successfully, 0 errors
[hashkill] CPU features: SSE2 SSE3
[hashkill] Detected 8 CPUs.
[hashkill] Found GPU device: NVIDIA Corporation - GeForce GTX 560 Ti
[hashkill] Temperature threshold set to 90 degrees C
[hashkill] GPU0: GeForce GTX 560 Ti [temp:70C]
[hashkill] Bruteforce charset (size=62): abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
[hashkill] Attack has O(N) complexity
[hashkill] This plugin supports GPU acceleration.
[hashkill](lzma/lzma.c:255) Can't open input file: /usr/local/share/hashkill/kernels/nvidia_desunix_long__sm21.ptx

[hashkill] Attack took 0 seconds.
[hashkill] Bye bye :)

Any hint on how to solve that out?
Cheers

**Comment by gat3way** [comment]
Hello grk-,
Are you running the program on the same system you built it? Nvidia unfortunately does not provide means to cross-compile kernels for hardware that is newer compute capability than the system installed one. The only solution to build all nvidia kernels is to do a build on a system with sm_30 hardware installed. So if you have built the kernels on a machine with sm_20 gpu, the sm_21 kernel won't get built. If you later copy the binaries on a sm_21 machine, the kernels would be missing.

Another reason for the missing kernel could be interrupted kernel build process, in which case some of the kernels might git omitted when you run make for the second time. This is easy to handle - just go to the source directory and type:

rm src/kernels/compiler/nvidia_desunix_long*
make && make install

**Comment by gat3way** [comment]
P.S your max length in this attack example is 10, the desunix algorithm supports passwords up to 8 characters (any longer password would get truncated to 8). You don't need to try passwords length 10 and 9. hashkill will handle that for you though, it will refuse to try candidates of len>8.

**Comment by grk-** [comment]
I've a fresh copy of hk and the module compiled correctly.
Thanks gat3way. Where shoud I deliver the beer? ;)
