### ISSUE TITLE
Recent keepass plugin does not support Nvidia GPU

### ISSUE THREAD

**Issue by grk-** [gat3way/hashkill#19]
I got the latest commit and got this compile error.
I'm obviously (and sadly) having a nvidia gpu.
# NVidia

Compiling nvidia_keepass without flags...
Unable to open ../nvidia_keepass.cl. Exiting.

Compiling nvidia_keepass2 without flags...
Unable to open ../nvidia_keepass2.cl. Exiting.
make[2]: **\* [build] Error 255

I had a look in src/kernels/compiler/Makefile and figured out that commenting following lines enabled compile process to go further and generate the hk binary:

176 if [ ! -e nvidia_keepass__sm10.ptx ]; then ./nvidia-compiler nvidia_keepass n ;fi; \
177 if [ ! -e nvidia_keepass2__sm10.ptx ]; then ./nvidia-compiler nvidia_keepass2 n ;fi; \

So either those ptx files have to be created (no sure what is it actually) either commenting/deleting those 2 lines.

grk

**Comment by gat3way** [comment]
Oooops....forgot to git add those. Commited, sorry.
