### ISSUE TITLE
minor bug in parallel build

### ISSUE THREAD

**Issue by ZeroChaos-** [gat3way/hashkill#38]
sometimes I get this since parallel build support was added:

make[2]: Entering directory `/var/tmp/portage/app-crypt/hashkill-9999/work/hashkill-9999/src/kernels/compiler'
cc -o amd-compiler compiler.c amd-compiler.c ../../lzma/7zFile.c ../../lzma/7zStream.c ../../lzma/LzmaDec.c ../../lzma/LzmaEnc.c ../../lzma/Alloc.c ../../lzma/LzFind.c ../../lzma/lzma.c -I../.. ../../ocl-base.c -Wno-unused-result -D_7ZIP_ST -ldl 
cc -o nvidia-compiler compiler.c nvidia-compiler.c ../../lzma/7zFile.c ../../lzma/7zStream.c ../../lzma/LzmaDec.c ../../lzma/LzmaEnc.c ../../lzma/Alloc.c ../../lzma/LzFind.c ../../lzma/lzma.c -I../.. ../../ocl-base.c -Wno-unused-result -D_7ZIP_ST -ldl  
paxctl -m _-compiler
nvidia-compiler: Invalid argument
make[2]: *_\* [amd-compiler] Error 1
make[2]: **\* Waiting for unfinished jobs....

it looks like my -j is too high and it tries to run the *-compiler before they are actually compiled.

side note, there is another bug open for the fact that even if I only request ati or nvidia both compilers are built

**Comment by gat3way** [comment]
Separated amd/nvidia-compiler targets in Makefile. Does that error persist?

**Comment by ZeroChaos-** [comment]
2/3 worked so far but yes, it still persists.

normally for things like this you would want to have a target to build the compilers and have the main target depend on the "build_compilers" target or something like that.  Your Makefile.am doesn't seem to have anything like that.

**Comment by gat3way** [comment]
I now get it what you mean. You need to have the kernel compiler binaries done before the rest. Need to think how to redesign the makefiles..

**Comment by gat3way** [comment]
Hm, wouldn't it be much more easier if we just put a dummy amd-compiler/nvidia-compiler binary in that directory? It would be later on overwritten by the compiler...

**Comment by ZeroChaos-** [comment]
please don't do that, it's not about hiding the issue, it is about fixing it.  if you have a dummy binary there my box has enough threads to start trying to compile using that dummy...  you need to build the compilers first, then build the rest.  commonly multiple makefile targets are used for this.

**Comment by gat3way** [comment]
No, that would not happen - because the way the Makefile is currently organized, all kernels are make targets. And all kernel compilation make targets depend on the compiler make target. It's something like that:

%: %.c 
        $(CC) -o $@ $< $(LZMA_SRC) $(OPENCL_SRC) -Wno-unused-result -D_7ZIP_ST -ldl

amd_ipb2_long: amd-compiler
                @if [ "$(CL_AMDFLAGS)" = "yes" ]; then \
                if [ ! -e amd_ipb2_long__Juniper.bin ]; then ./amd-compiler amd_ipb2_long n ;fi; \
                fi

So in order to build amd_ipb2_long, you already need amd-compiler compiled. I don't think (though I am stupid I know) there might be a race between building the compiler and using the compiler to build the kernel.

However, I think paxctl is being executed some time before amd-compiler is being built, thus having a dummy binary as ugly as it sounds will fix the problem. However I don't know when exactly paxctl is being called, perhaps there is a much better solution than this.

**Comment by ZeroChaos-** [comment]
oh, looks like that is our fault.  my apologies, I'll move our paxctl somewhere sane.  Got any suggestions for a place I can run paxctl on the compiled *-compiler but before they are used?

**Comment by gat3way** [comment]
Umm not quite sure how the build system you use works and where can that be done. Still, the dummy binaries would solve the problem I think.

**Comment by ZeroChaos-** [comment]
The dummy binaries would actually cause build failures as well.  Don't worry about this one, it's our fault, I'll handle it ;-)  thanks for the clarifications.
