### ISSUE TITLE
configuration scripts break common rules

### ISSUE THREAD

**Issue by blshkv** [gat3way/hashkill#5]
I've created an ebuild for Pentoo Linux (https://code.google.com/p/pentoo/source/browse/portage/trunk/app-crypt/hashkill/hashkill-0.3.0.ebuild)  but it was a pain.

Here is the list of problems:
- do not install anything during the "make" stage. Fixed in lines 22-24
- respect the prefix path. Fixed in lines 26-33
- missing prefix/usr/bin directory. Fixed in lines 46-47
- missing opencl options as specified in "Installing with GPU support" section.
- the LTO optimisation is hardcoded in the configure script

Hope you can clean up the automake and Makefiles scripts

**Comment by gat3way** [comment]
Hello blkshv,

Those three:
- do not install anything during the "make" stage. Fixed in lines 22-24
- respect the prefix path. Fixed in lines 26-33
- missing prefix/usr/bin directory. Fixed in lines 46-47

I am going to fix soon, they are stupid indeed.

This one:
- missing opencl options as specified in "Installing with GPU support" section.

Is weird. There used to be such section in the README but I am sure I removed it (as it now auto-detects OpenCL in build-time and also it does not link against the opencl library). I also can't find it in the git repo. There used to be an --with-opencl=... option, but it was dropped. This is rather embarassing to me, looks like the source tarball was made out of my backup tree which did not have those changes applied (?). Will now have a look.

And this one:
- the LTO optimisation is hardcoded in the configure script

is something I am not willing to change unless there is a good reason for that. It has significant benefits. Rather than that, I think it would be better if I do a configure-time check for gcc>=4.6 and refuse to build with older gcc versions. Yes, this hurts older systems. What do you think is the better solution?

**Comment by blshkv** [comment]
> What do you think is the better solution?

I suggest to point it out in the requirements but leave the script as it is now. I don't think that many distributions have 4.6 stabilized by now. There are number of bugs opened in https://bugs.gentoo.org at least. BTW, gcc 4.5 does support LTO, it is just not enabled by default. I'll test the 4.5 version with it enabled and report back in the bug #4. Thanks.

ps. yes, opencl section is in the INSTALL file which exists in the source tar-ball.

**Comment by gat3way** [comment]
blkshv, I fixed the all: install rules. However, I am confused about the missing prefix. When I pass --prefix=... to ./configure, I see it prepended to my $(DATADIR) and $(BINDIR) variables. Is there something I am missing about it?

**Comment by blshkv** [comment]
Sorry, the problem is with the DESTDIR, not with the prefix. Here is the documentation:
http://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by gat3way** [comment]
Fixed $(CFLAGS) $(LDFLAGS).

Fixed that $(DESTDIR) problem as well.

Closing the issue

**Comment by blshkv** [comment]
it's getting better. However you missed markov/Makefile and tools/Makefile at least. Please double check.

**Comment by gat3way** [comment]
Sorry, must have forgotten them. Fixed.

**Comment by blshkv** [comment]
ok, we are almost done ;-) There are just few QA notices left:
- QA Notice: Pre-stripped files found:
- /usr/bin/hashkill
  see: http://www.gentoo.org/proj/en/qa/backtraces.xml
  Note: Some packages unfortunately handle stripping by themselves, inside the upstream provided makefiles. This is an error and should be reported. All packages should leave Portage the task of the stripping or simply restrict stripping entirely. The main exception to this are binary packages. They are usually stripped by upstream, outside of Portage control.
- QA Notice: Files built without respecting LDFLAGS have been detected
-  Please include the following list of files in your report:
- /usr/bin/pcap2hcap
- /usr/share/hashkill/plugins/rar.so

You can probably remove build-in switches and optimization or move $(LDFLAGS) to the end of line to overwrite them.

Also, I had to patch ltmain.sh file like this to fix "version mismatch" error message:
https://code.google.com/p/pentoo/source/browse/portage/trunk/app-crypt/hashkill/files/hashkill-automake.patch

Let me know if you need more info.

**Comment by gat3way** [comment]
Agreed, no need to strip there, there is an install-strip target anyway. Removed
pcap2hcap is fixed. rar is.....hmmmm rather strange.

As far as the ltmain.sh stuff is concerned, I don't think I've got a good solution to this. Running ./rebuild.sh should solve it for you.

**Comment by blshkv** [comment]
ok, so it's only the rar plugin warning left.

as for the rebuild.sh, I tried it, but it didn't help.
Here is the output (full of warnings btw)
http://pastebin.com/fMi4BRX8
 and (with ltmain.sh regenerated)
http://pastebin.com/y3nPQtxx

ltmain.sh: Version mismatch error.  This is libtool 2.4, but the
ltmain.sh: definition of this LT_INIT comes from an older release.
ltmain.sh: You should recreate aclocal.m4 with macros from libtool 2.4
ltmain.sh: and run autoconf again.

**Comment by gat3way** [comment]
Hi,

Could you retry with the most recent rebuild.sh from the latest commit?

**Comment by blshkv** [comment]
no, still does not work. It generates ltmain.sh from the second run only, and it fails with the error as above:
http://pastebin.com/Q6W4CnxW

**Comment by gat3way** [comment]
That's very confusing....I can't find out where does the debian libtool version come from. Evil autoconf :(

**Comment by blshkv** [comment]
The problem is somewhere around line #976 (ltmain.sh), the "$macro_version" variable is empty actually

**Comment by gat3way** [comment]
ltmain.sh should be regenerated with the latest rebuild.sh (in fact the old one is being deleted). Damn :(

Googling about that, some people apparently suggested running "libtoolize --force". I updated rebuild.sh in git. Can you please once again retry?

**Comment by blshkv** [comment]
ok, it regenerates ltmain from the first time, but the problem is still there:
http://pastebin.com/qW2CjNqL

We need to figure out where that macro_version should come from.

How about if you start fixing these configure.ac warning messages first?

**Comment by gat3way** [comment]
I think i finally fixed that. Please try the newest git files. Changes were made to configure.ac, Makefile.am and rebuild.sh

**Comment by ghost** [comment]
Now is fails at the beginning of the build:

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: executing libtool commands
config.status: executing depfiles commands
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/spirtbrat/.yaourt/hashkill-git/src/hashkill-build/missing --run aclocal-1.11
/home/spirtbrat/.yaourt/hashkill-git/src/hashkill-build/missing: line 52: aclocal-1.11: command not found
WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/spirtbrat/.yaourt/hashkill-git/src/hashkill-build/missing --run autoconf
 cd . && /bin/sh /home/spirtbrat/.yaourt/hashkill-git/src/hashkill-build/missing --run automake-1.11 --foreign
/home/spirtbrat/.yaourt/hashkill-git/src/hashkill-build/missing: line 52: automake-1.11: command not found
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
aclocal.m4:16: warning: this file was generated for autoconf 2.64.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically `autoreconf'.
configure.ac:15: error: possibly undefined macro: AM_PROG_CC_C_O
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
make: *** [configure] Error 1
```

It was building fine several commits ago.

**Comment by blshkv** [comment]
yes, the current ltmain.sh runs fine, however the rebuild.sh regenerates it badly again

ltmain.sh: Version mismatch error.  This is libtool 2.4, but the
ltmain.sh: definition of this LT_INIT comes from an older release.
ltmain.sh: You should recreate aclocal.m4 with macros from libtool 2.4
ltmain.sh: and run autoconf again.

**Comment by gat3way** [comment]
blshkv could you retry?

**Comment by blshkv** [comment]
not fixed ..

**Comment by gat3way** [comment]
Could you git clone in a new workspace then run ./rebuild.sh prior to build? If the error persists, please attach the build output.

**Comment by blshkv** [comment]
commit number: 91b5800fd268b16dc9dda48362e4340281e21b5a

The current ltmain.sh is broken now as well.

bash# ./rebuild.sh 
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file`./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file`m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file`m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file`m4/lt~obsolete.m4'
autoreconf-2.68: Entering directory `.'
autoreconf-2.68: configure.ac: not using Gettext
autoreconf-2.68: running: aclocal -I m4
autoreconf-2.68: configure.ac: tracing
autoreconf-2.68: running: libtoolize --copy
autoreconf-2.68: running: /usr/bin/autoconf-2.68
autoreconf-2.68: configure.ac: not using Autoheader
autoreconf-2.68: running: automake --add-missing --copy --no-force
autoreconf-2.68: Leaving directory`.'

bash# ./ltmain.sh 
./ltmain.sh: line 125: CDPATH: command not found
ltmain.sh: Version mismatch error.  This is libtool 2.4, but the
ltmain.sh: definition of this LT_INIT comes from an older release.
ltmain.sh: You should recreate aclocal.m4 with macros from libtool 2.4
ltmain.sh: and run autoconf again.

I modified line 992 to display variables like that:
  $progname: definition of this LT_INIT comes from an older release: "$package_revision" and "$macro_revision"

Here is the output:
  ltmain.sh: definition of this LT_INIT comes from an older release: "1.3293" and ""

**Comment by gat3way** [comment]
Hello, 

As advised here:
http://stackoverflow.com/questions/7726649/library-fails-to-build-if-autoreconf-i-is-run-before-configure

I decided to include everything recreated by autoreconf locally. It should (hopefully) build now. Please do not run rebuild.sh prior to that.

**Comment by blshkv** [comment]
ok, it builds fine again with the updated ltmain.sh.

we are back to the main issue:
- QA Notice: Pre-stripped files found:
- /usr/share/hashkill/plugins/zip.so
- /usr/share/hashkill/plugins/wpa.so
- /usr/share/hashkill/plugins/wordpress.so
- /usr/share/hashkill/plugins/vbulletin.so
- /usr/share/hashkill/plugins/smf.so
- /usr/share/hashkill/plugins/sl3.so
- /usr/share/hashkill/plugins/sha512unix.so
- /usr/share/hashkill/plugins/sha512.so
- /usr/share/hashkill/plugins/sha256.so
- /usr/share/hashkill/plugins/sha1sha1.so
- /usr/share/hashkill/plugins/sha1.so
- /usr/share/hashkill/plugins/sapg.so
- /usr/share/hashkill/plugins/ripemd160.so
- /usr/share/hashkill/plugins/privkey.so
- /usr/share/hashkill/plugins/pixmd5.so
- /usr/share/hashkill/plugins/phpbb3.so
- /usr/share/hashkill/plugins/osxlion.so
- /usr/share/hashkill/plugins/osx-old.so
- /usr/share/hashkill/plugins/oracle11g.so
- /usr/share/hashkill/plugins/oracle-old.so
- /usr/share/hashkill/plugins/ntlm.so
- /usr/share/hashkill/plugins/mysql5.so
- /usr/share/hashkill/plugins/mssql-2005.so
- /usr/share/hashkill/plugins/mssql-2000.so
- /usr/share/hashkill/plugins/mscash2.so
- /usr/share/hashkill/plugins/mscash.so
- /usr/share/hashkill/plugins/mediawiki.so
- /usr/share/hashkill/plugins/md5unix.so
- /usr/share/hashkill/plugins/md5md5.so
- /usr/share/hashkill/plugins/md5.so
- /usr/share/hashkill/plugins/md5-saltpass.so
- /usr/share/hashkill/plugins/md5-passsalt.so
- /usr/share/hashkill/plugins/md4.so
- /usr/share/hashkill/plugins/lm.so
- /usr/share/hashkill/plugins/ldap-ssha.so
- /usr/share/hashkill/plugins/ldap-sha.so
- /usr/share/hashkill/plugins/ipb2.so
- /usr/share/hashkill/plugins/dmg.so
- /usr/share/hashkill/plugins/desunix.so
- /usr/share/hashkill/plugins/bfunix.so
- /usr/share/hashkill/plugins/apr1.so
- QA Notice: Files built without respecting LDFLAGS have been detected
-  Please include the following list of files in your report:
- /usr/share/hashkill/plugins/rar.so

**Comment by gat3way** [comment]
the .so files should not be stripped with the latest commit. Not quite sure about that rar...it's quite strange as it includes $(LDFLAGS)...

**Comment by blshkv** [comment]
Remove src/plugins/rar.so.  It does not get rebuild because of "@if [ ! -e rar.so ]; "

What a bug! It took me 20min to figure it out ;-\

ps. Would be good if you could release a new version at some point.

**Comment by gat3way** [comment]
Done. 

A new version will be out soon, need 1-2 more plugins to add and test.

**Comment by gat3way** [comment]
P.S everything building correctly now? May I close the issue?

**Comment by blshkv** [comment]
yes, we are good. Thank you for your quick responds.
